### PR TITLE
Fix Collection.to_dict() to support array of links with same link rel…

### PR DESCRIPTION
**Pull request by brianfpeters**
Fix Collection.to_dict() to support array of links with same link relation as per section 4.1.1 of draft RFC. [https://tools.ietf.org/html/draft-kelly-json-hal-07]

If a link is the second to use a previous relation then the first link's body is moved inside a list and the second link's body is appended to that list.

Otherwise use the dict.upate() function as before.

### CODE REVIEW

**Comment by radeklos** [comment]
@brianfpeters Can you please add some tests?

**Comment by brianfpeters** [comment]
Ok. Thanks for the patience (regarding former PR#20). It may be the weekend before I can get some more time for it, so if I go quiet for a bit it doesn't mean I've buggered off. It means I'm tracking down the test code.

**Comment by krak3n** [comment]
@brianfpeters ya didn't need to close it 😄

**Comment by brianfpeters** [comment]
Just added tests and verified all pass. Even managed to track down python3.3 from the deadsnakes ppa. (gotta love that name!)

**Comment by radeklos** [comment]
@brianfpeters: thank for the test. Can you please update version in VERSION file to 1.0.2 and update change log? Once this will be done I think that we can merge this and release it :)

**Comment by brianfpeters** [comment]
Done and done! cheers

**Comment by krak3n** [comment]
Thanks @brianfpeters 👍

**Pull request merged**
