### PR TITLE
Feature: Response Class

### PR DESCRIPTION
**Pull request by krak3n**
A custom response class which handles converting `flask_hal.document.Document` view return values into standard `flask.Response` objects.

This means views still follow the standard `tuple` return value pattern and can still return none `HAL` document responses if needed.

The user also has the ability to set their own `response_class` if needed.

### CODE REVIEW

**Comment by krak3n** [comment]
### Example

``` python
# Third Party Libs
from flask import Flask

# First Party Libs
from flask_hal import HAL, document


app = Flask(__name__)
HAL(app)  # Initialise HAL


@app.route('/hello')
def hello():
    return document.Document(data={
        'message': 'Hello World'
    })


if __name__ == "__main__":
    app.run(debug=True)
```

``` http
GET /hello HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:5000
User-Agent: HTTPie/0.9.2

HTTP/1.0 200 OK
Content-Length: 87
Content-Type: application/hal+json
Date: Thu, 06 Aug 2015 14:12:37 GMT
Server: Werkzeug/0.10.4 Python/2.7.6

{
    "_links": {
        "self": {
            "href": "http://localhost:5000/hello"
        }
    },
    "message": "Hello World"
}
```

**Comment by krak3n** [comment]
@peeklondon & @radeklos :eyes: pwease :smile:

**Comment by gregatsoon** [comment]
nice, I like :+1:

**Comment by radeklos** [comment]
:+1:

**Pull request merged**
