### PR TITLE
new folder structure - packaging, setup.py, empty tox

### PR DESCRIPTION
**Pull request by radeklos**
I've changed project structure to separate dockerfile, sourcefiles, test, ...

### CODE REVIEW

**Comment by radeklos** [comment]
@krak3n @peeklondon CR please.

**Comment by krak3n** [comment]
Why do we need to move files to `src` dir?

**Comment by radeklos** [comment]
Because root dir gets messy with all files like - readme, licence, circle, dockerfile, ... and i prefer to keep source files out of all those files. It could be just flask_hal but then you have nested tests inside that dir..

**Comment by krak3n** [comment]
IMO I don't think putting things a `src` dir solves anything other than hiding stuff away into another dir. Either way source files will still won't be in the root anyway other than `setup.py`, which really should be in the root so it can be easily `pip` / `easy_install` installable. 

The dir structure should really follow normal Python conventions unless there is a build requirement for it to live in a `src` or `lib` dir. 

I just think it makes the project harder to work with.

```
- docs
  - ...
- module
  - __init__.py
  - ...
- tests
  - __init__.py
  - ...
- README.md
- setup.py
```

**Comment by radeklos** [comment]
@krak3n  I've put project structure back. 

I've added circle config to run tests in tox..

**Comment by krak3n** [comment]
Thanks :+1:

**Pull request merged**
